
debug: true 
server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never


  datasource:
    url: jdbc:postgresql://localhost:5432/beeCarefull_db
    username: beeCarefull_user
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      '[hibernate.format_sql]': true
    #image
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 2MB
 




logging:
  file:
    name: log/beeCarefull.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    '[org.springframework.web]': warn
    '[org.hibernate]': info
    '[com.gaming]': debug
    '[org.springframework.boot.autoconfigure]': error
    root: off

management: #actuator
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

gamingProM:
  app:
    jwtSecret: beeCarefull@!123
    jwtExpirationMs: 86400000

info:
  application:
    name: 'beeCarefull backend Project'
    description: 'This is bee and honey netwok Backend Project'
    version: '@project.version@'
  
      

  
   